flags: {}
extra-package-dbs: []
packages:
  - '.'
resolver: lts-21.25
compiler-check: newer-minor
extra-deps:
  - gi-gst-1.0.30
  - gi-gstbase-1.0.29
  - gi-gstvideo-1.0.29
  - haskell-gi-0.26.17
  - haskell-gi-base-0.26.9
